WIFI_SSID = 'DIGIFIBRA-27Z9'
WIFI_PASSWORD = 'DCtyckPXhYD5'

MQTT_BROKER = '192.168.1.149'
MQTT_PORT = 1883
MQTT_CLIENT = 'pico1'
MQTT_TOPIC = 'planta/sensores'

# SENSOR
PIN_ADC = 26

# PANTALLA ST7735S
SPI_MOSI = 19
SPI_SCK  = 18

LCD_CS   = 4
LCD_DC   = 5
LCD_RST  = 6

# CALIBRACIÓN
ADC_SECO = 52000
ADC_MOJADO = 20000

# UMBRALES
UMBRAL_SECO = 30
UMBRAL_BIEN = 60
INTERVALO_S = 30

# IMÁGENES (YA EN RAW)
IMG_FELIZ = 'feliz.raw'
IMG_NORMAL = 'normal.raw'
IMG_TRISTE = 'triste.raw'
