WIFI_SSID = 'NombreDeTuRed'
WIFI_PASSWORD = 'TuContrasena'

MQTT_BROKER = '192.168.1.100'
MQTT_PORT = 1883
MQTT_CLIENT = 'pico_planta'
MQTT_TOPIC = 'planta/sensores'

PIN_HUMEDAD = 26  # GP26 / ADC0
PIN_DHT22 = 15    # GP15
PIN_SDA = 4       # GP4 I2C
PIN_SCL = 5       # GP5 I2C

ADC_SECO = 52000
ADC_MOJADO = 20000

UMBRAL_SECO = 30  #PLANTA TRISTE
UMBRAL_BIEN = 60  #PLANTA FELIZ
INTERVALO_S = 30  #SEGUNDOS ENTRE LECTURAS

IMG_FELIZ = 'feliz.pbm'
IMG_NORMAL = 'normal.pbm'
IMG_TRISTE = 'triste.pbm'
